language: go
go:
  - 1.2

install:
  - go get -d -v code.google.com/p/graphics-go/graphics
  - go get -d -v launchpad.net/gocheck
  - go get -d -v labix.org/v2/mgo 
  - go get -d -v github.com/gorilla/mux
