language: go
go:
  - 1.5
  - tip

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq imagemagick

services: mongodb

install:
    - go get -t -d -v ./...
    - go get github.com/onsi/ginkgo/ginkgo

script:
    - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
