language: go
go:
  - 1.1

install:
  - go get code.google.com/p/graphics-go/graphics
  - go get launchpad.net/gocheck
  - go get github.com/kr/godep 
  - go get labix.org/v2/mgo 
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
  - go get github.com/gorilla/sessions 